services:
  db:
    image: docker.io/postgres:15-alpine
    container_name: mart_it_db
    restart: always
    environment:
      POSTGRES_USER: mart_user
      POSTGRES_PASSWORD: mart_password
      POSTGRES_DB: mart_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: docker.io/redis:7-alpine
    container_name: mart_it_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: